# Generated by Django 5.0.1 on 2024-02-24 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=75)),
                ('name', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=75)),
                ('born_year', models.DateField()),
                ('pages', models.PositiveSmallIntegerField()),
                ('amount', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Books',
        ),
    ]
