# Generated by Django 5.0.1 on 2024-02-27 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_genre_book_public_office'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='amount',
        ),
        migrations.AlterField(
            model_name='book',
            name='born_year',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='book',
            name='pages',
            field=models.CharField(max_length=10),
        ),
    ]
