# Generated by Django 5.0.1 on 2024-02-27 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_book_author_remove_book_born_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.TextField(default=' '),
        ),
        migrations.AddField(
            model_name='book',
            name='born_year',
            field=models.TextField(default=' '),
        ),
        migrations.AddField(
            model_name='book',
            name='name',
            field=models.TextField(default=' '),
        ),
        migrations.AddField(
            model_name='book',
            name='pages',
            field=models.TextField(default=' '),
        ),
        migrations.AddField(
            model_name='book',
            name='public_office',
            field=models.TextField(default=' '),
        ),
    ]
