# Generated by Django 5.0.1 on 2024-02-27 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_book_author_book_born_year_book_name_book_pages_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
