# Generated by Django 5.0.1 on 2024-02-27 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0007_delete_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.TextField(default=' ')),
                ('name', models.TextField(default=' ')),
                ('public_office', models.TextField(default=' ')),
                ('born_year', models.TextField(default=' ')),
                ('pages', models.TextField(default=' ')),
            ],
        ),
    ]
