# Generated by Django 5.0.1 on 2024-02-27 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='Book2',
        ),
    ]
