# Generated by Django 5.0.1 on 2024-02-27 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book2',
        ),
    ]
